version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8080:8080"